- name: Demo on ansible tags
  hosts: TEST
  tasks:
    - name: T1
      debug: 
        msg: "Task1 -- install tag"
      tags:
         - install

    - name: T2
      debug:
        msg: "Task2 -- config tag"
      tags:
         - config
